name: Automated niv-managed dependency updates
on:
  schedule:
    # every day at 4:00am
    - cron:  '0 4 * * *'
  workflow_dispatch:
jobs:
  niv-updater:
    name: 'Create PRs for niv-managed dependencies'
    runs-on: ubuntu-latest
    steps:
      - name: niv-updater-action
        uses: knl/niv-updater-action@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pull_request_base: 'development'
          sources_file: 'nix/sources.json'
          branch_prefix: 'niv-update/'
